// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCXv9UyRCMYfaNA9aybkik_rTe1CdToiU',
    appId: '1:493909958756:web:af53e7712e9354f8cd3f71',
    messagingSenderId: '493909958756',
    projectId: 'attendance-record---flutter',
    authDomain: 'attendance-record---flutter.firebaseapp.com',
    databaseURL: 'https://attendance-record---flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'attendance-record---flutter.appspot.com',
    measurementId: 'G-KRH6VGV7D6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgjR71Wdy7Xx0aeOjyxFT7Grx8lkhCd-g',
    appId: '1:493909958756:android:c7378e7894557746cd3f71',
    messagingSenderId: '493909958756',
    projectId: 'attendance-record---flutter',
    databaseURL: 'https://attendance-record---flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'attendance-record---flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv9DqZKmcsTbf5-wtosYRcnCFHQF_N53g',
    appId: '1:493909958756:ios:71cafd7d7b49d7d8cd3f71',
    messagingSenderId: '493909958756',
    projectId: 'attendance-record---flutter',
    databaseURL: 'https://attendance-record---flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'attendance-record---flutter.appspot.com',
    iosClientId: '493909958756-stn6k1rs15g9rtm6ojvgi4dlm4jrgjq3.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendancerecords',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv9DqZKmcsTbf5-wtosYRcnCFHQF_N53g',
    appId: '1:493909958756:ios:71cafd7d7b49d7d8cd3f71',
    messagingSenderId: '493909958756',
    projectId: 'attendance-record---flutter',
    databaseURL: 'https://attendance-record---flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'attendance-record---flutter.appspot.com',
    iosClientId: '493909958756-stn6k1rs15g9rtm6ojvgi4dlm4jrgjq3.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendancerecords',
  );
}
